language: python

git:
  depth: 1

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: yes

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - poetry run make test

after_success:
  - poetry run make coverage
