version: '3'

volumes:
  db_data: {}

services:
  db:
    network_mode: host
    image: rethinkdb:2.3
    container_name: starbelly-dev-db
    volumes:
      - db_data:/data

  web:
    network_mode: host
    image: nginx:1.15
    container_name: starbelly-dev-web
    volumes:
      - "${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "${PWD}/server.crt:/etc/nginx/server.crt"
