# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import shared_pb2 as protobuf_dot_shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/server.proto',
  package='starbelly',
  syntax='proto2',
  serialized_pb=_b('\n\x15protobuf/server.proto\x12\tstarbelly\x1a\x15protobuf/shared.proto\"\xc2\x01\n\x05\x45vent\x12\x17\n\x0fsubscription_id\x18\x01 \x02(\x05\x12*\n\ncrawl_item\x18\x02 \x01(\x0b\x32\x14.starbelly.CrawlItemH\x00\x12.\n\x0cjob_statuses\x18\x03 \x01(\x0b\x32\x16.starbelly.JobStatusesH\x00\x12<\n\x13subscription_closed\x18\x04 \x01(\x0b\x32\x1d.starbelly.SubscriptionClosedH\x00\x42\x06\n\x04\x42ody\"\xe8\x01\n\x08Response\x12\x12\n\nrequest_id\x18\x01 \x02(\x05\x12\x12\n\nis_success\x18\x02 \x02(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12,\n\x07new_job\x18\x04 \x01(\x0b\x32\x19.starbelly.ResponseNewJobH\x00\x12>\n\x10new_subscription\x18\x06 \x01(\x0b\x32\".starbelly.ResponseNewSubscriptionH\x00\x12\'\n\x04ping\x18\x05 \x01(\x0b\x32\x17.starbelly.ResponsePingH\x00\x42\x06\n\x04\x42ody\" \n\x0eResponseNewJob\x12\x0e\n\x06job_id\x18\x01 \x02(\x0c\"2\n\x17ResponseNewSubscription\x12\x17\n\x0fsubscription_id\x18\x01 \x02(\x05\"\x1c\n\x0cResponsePing\x12\x0c\n\x04pong\x18\x01 \x01(\t\"j\n\rServerMessage\x12!\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x10.starbelly.EventH\x00\x12\'\n\x08response\x18\x02 \x01(\x0b\x32\x13.starbelly.ResponseH\x00\x42\r\n\x0bMessageType\"\x86\x01\n\x12SubscriptionClosed\x12\x34\n\x06reason\x18\x01 \x02(\x0e\x32$.starbelly.SubscriptionClosed.Reason\x12\x0f\n\x07message\x18\x02 \x01(\t\")\n\x06Reason\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x07\n\x03\x45ND\x10\x02\x12\t\n\x05\x45RROR\x10\x03')
  ,
  dependencies=[protobuf_dot_shared__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SUBSCRIPTIONCLOSED_REASON = _descriptor.EnumDescriptor(
  name='Reason',
  full_name='starbelly.SubscriptionClosed.Reason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='END', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=809,
  serialized_end=850,
)
_sym_db.RegisterEnumDescriptor(_SUBSCRIPTIONCLOSED_REASON)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='starbelly.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscription_id', full_name='starbelly.Event.subscription_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crawl_item', full_name='starbelly.Event.crawl_item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job_statuses', full_name='starbelly.Event.job_statuses', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subscription_closed', full_name='starbelly.Event.subscription_closed', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Body', full_name='starbelly.Event.Body',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=60,
  serialized_end=254,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='starbelly.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='starbelly.Response.request_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_success', full_name='starbelly.Response.is_success', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='starbelly.Response.error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_job', full_name='starbelly.Response.new_job', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_subscription', full_name='starbelly.Response.new_subscription', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ping', full_name='starbelly.Response.ping', index=5,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Body', full_name='starbelly.Response.Body',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=257,
  serialized_end=489,
)


_RESPONSENEWJOB = _descriptor.Descriptor(
  name='ResponseNewJob',
  full_name='starbelly.ResponseNewJob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='starbelly.ResponseNewJob.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=523,
)


_RESPONSENEWSUBSCRIPTION = _descriptor.Descriptor(
  name='ResponseNewSubscription',
  full_name='starbelly.ResponseNewSubscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscription_id', full_name='starbelly.ResponseNewSubscription.subscription_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=575,
)


_RESPONSEPING = _descriptor.Descriptor(
  name='ResponsePing',
  full_name='starbelly.ResponsePing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pong', full_name='starbelly.ResponsePing.pong', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=605,
)


_SERVERMESSAGE = _descriptor.Descriptor(
  name='ServerMessage',
  full_name='starbelly.ServerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='starbelly.ServerMessage.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='starbelly.ServerMessage.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MessageType', full_name='starbelly.ServerMessage.MessageType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=607,
  serialized_end=713,
)


_SUBSCRIPTIONCLOSED = _descriptor.Descriptor(
  name='SubscriptionClosed',
  full_name='starbelly.SubscriptionClosed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='starbelly.SubscriptionClosed.reason', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='starbelly.SubscriptionClosed.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUBSCRIPTIONCLOSED_REASON,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=850,
)

_EVENT.fields_by_name['crawl_item'].message_type = protobuf_dot_shared__pb2._CRAWLITEM
_EVENT.fields_by_name['job_statuses'].message_type = protobuf_dot_shared__pb2._JOBSTATUSES
_EVENT.fields_by_name['subscription_closed'].message_type = _SUBSCRIPTIONCLOSED
_EVENT.oneofs_by_name['Body'].fields.append(
  _EVENT.fields_by_name['crawl_item'])
_EVENT.fields_by_name['crawl_item'].containing_oneof = _EVENT.oneofs_by_name['Body']
_EVENT.oneofs_by_name['Body'].fields.append(
  _EVENT.fields_by_name['job_statuses'])
_EVENT.fields_by_name['job_statuses'].containing_oneof = _EVENT.oneofs_by_name['Body']
_EVENT.oneofs_by_name['Body'].fields.append(
  _EVENT.fields_by_name['subscription_closed'])
_EVENT.fields_by_name['subscription_closed'].containing_oneof = _EVENT.oneofs_by_name['Body']
_RESPONSE.fields_by_name['new_job'].message_type = _RESPONSENEWJOB
_RESPONSE.fields_by_name['new_subscription'].message_type = _RESPONSENEWSUBSCRIPTION
_RESPONSE.fields_by_name['ping'].message_type = _RESPONSEPING
_RESPONSE.oneofs_by_name['Body'].fields.append(
  _RESPONSE.fields_by_name['new_job'])
_RESPONSE.fields_by_name['new_job'].containing_oneof = _RESPONSE.oneofs_by_name['Body']
_RESPONSE.oneofs_by_name['Body'].fields.append(
  _RESPONSE.fields_by_name['new_subscription'])
_RESPONSE.fields_by_name['new_subscription'].containing_oneof = _RESPONSE.oneofs_by_name['Body']
_RESPONSE.oneofs_by_name['Body'].fields.append(
  _RESPONSE.fields_by_name['ping'])
_RESPONSE.fields_by_name['ping'].containing_oneof = _RESPONSE.oneofs_by_name['Body']
_SERVERMESSAGE.fields_by_name['event'].message_type = _EVENT
_SERVERMESSAGE.fields_by_name['response'].message_type = _RESPONSE
_SERVERMESSAGE.oneofs_by_name['MessageType'].fields.append(
  _SERVERMESSAGE.fields_by_name['event'])
_SERVERMESSAGE.fields_by_name['event'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['MessageType']
_SERVERMESSAGE.oneofs_by_name['MessageType'].fields.append(
  _SERVERMESSAGE.fields_by_name['response'])
_SERVERMESSAGE.fields_by_name['response'].containing_oneof = _SERVERMESSAGE.oneofs_by_name['MessageType']
_SUBSCRIPTIONCLOSED.fields_by_name['reason'].enum_type = _SUBSCRIPTIONCLOSED_REASON
_SUBSCRIPTIONCLOSED_REASON.containing_type = _SUBSCRIPTIONCLOSED
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ResponseNewJob'] = _RESPONSENEWJOB
DESCRIPTOR.message_types_by_name['ResponseNewSubscription'] = _RESPONSENEWSUBSCRIPTION
DESCRIPTOR.message_types_by_name['ResponsePing'] = _RESPONSEPING
DESCRIPTOR.message_types_by_name['ServerMessage'] = _SERVERMESSAGE
DESCRIPTOR.message_types_by_name['SubscriptionClosed'] = _SUBSCRIPTIONCLOSED

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'protobuf.server_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.Event)
  ))
_sym_db.RegisterMessage(Event)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'protobuf.server_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.Response)
  ))
_sym_db.RegisterMessage(Response)

ResponseNewJob = _reflection.GeneratedProtocolMessageType('ResponseNewJob', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSENEWJOB,
  __module__ = 'protobuf.server_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.ResponseNewJob)
  ))
_sym_db.RegisterMessage(ResponseNewJob)

ResponseNewSubscription = _reflection.GeneratedProtocolMessageType('ResponseNewSubscription', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSENEWSUBSCRIPTION,
  __module__ = 'protobuf.server_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.ResponseNewSubscription)
  ))
_sym_db.RegisterMessage(ResponseNewSubscription)

ResponsePing = _reflection.GeneratedProtocolMessageType('ResponsePing', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEPING,
  __module__ = 'protobuf.server_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.ResponsePing)
  ))
_sym_db.RegisterMessage(ResponsePing)

ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), dict(
  DESCRIPTOR = _SERVERMESSAGE,
  __module__ = 'protobuf.server_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.ServerMessage)
  ))
_sym_db.RegisterMessage(ServerMessage)

SubscriptionClosed = _reflection.GeneratedProtocolMessageType('SubscriptionClosed', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIPTIONCLOSED,
  __module__ = 'protobuf.server_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.SubscriptionClosed)
  ))
_sym_db.RegisterMessage(SubscriptionClosed)


# @@protoc_insertion_point(module_scope)
