# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/shared.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/shared.proto',
  package='starbelly',
  syntax='proto2',
  serialized_pb=_b('\n\x15protobuf/shared.proto\x12\tstarbelly\"\xcc\x02\n\tCrawlItem\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ompleted_at\x18\x02 \x01(\t\x12\x0c\n\x04\x63ost\x18\x03 \x01(\x01\x12\x10\n\x08\x64uration\x18\x04 \x01(\x01\x12\x32\n\x07headers\x18\x05 \x03(\x0b\x32!.starbelly.CrawlItem.HeadersEntry\x12\x0e\n\x06job_id\x18\x06 \x01(\x0c\x12\x1a\n\x12is_body_compressed\x18\x07 \x01(\x08\x12\x12\n\nstarted_at\x18\x08 \x01(\t\x12\x13\n\x0bstatus_code\x18\t \x01(\x05\x12\x0b\n\x03url\x18\n \x01(\t\x12\x0f\n\x07url_can\x18\x0b \x01(\t\x12\x10\n\x08url_hash\x18\x0c \x01(\x0c\x12\x12\n\nsync_token\x18\r \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb8\x02\n\tJobStatus\x12\x0e\n\x06job_id\x18\x01 \x02(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12)\n\trun_state\x18\x03 \x01(\x0e\x32\x16.starbelly.JobRunState\x12\x12\n\nitem_count\x18\x04 \x01(\x05\x12\x1a\n\x12http_success_count\x18\x05 \x01(\x05\x12\x18\n\x10http_error_count\x18\x06 \x01(\x05\x12\x17\n\x0f\x65xception_count\x18\x07 \x01(\x05\x12\x46\n\x12http_status_counts\x18\x08 \x03(\x0b\x32*.starbelly.JobStatus.HttpStatusCountsEntry\x1a\x37\n\x15HttpStatusCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"5\n\x0bJobStatuses\x12&\n\x08statuses\x18\x01 \x03(\x0b\x32\x14.starbelly.JobStatus*^\n\x0bJobRunState\x12\x0b\n\x07UNKNOWN\x10\x01\x12\r\n\tCANCELLED\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\n\n\x06PAUSED\x10\x04\x12\x0b\n\x07PENDING\x10\x05\x12\x0b\n\x07RUNNING\x10\x06')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_JOBRUNSTATE = _descriptor.EnumDescriptor(
  name='JobRunState',
  full_name='starbelly.JobRunState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCELLED', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAUSED', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=741,
  serialized_end=835,
)
_sym_db.RegisterEnumDescriptor(_JOBRUNSTATE)

JobRunState = enum_type_wrapper.EnumTypeWrapper(_JOBRUNSTATE)
UNKNOWN = 1
CANCELLED = 2
COMPLETED = 3
PAUSED = 4
PENDING = 5
RUNNING = 6



_CRAWLITEM_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='starbelly.CrawlItem.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='starbelly.CrawlItem.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='starbelly.CrawlItem.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=369,
)

_CRAWLITEM = _descriptor.Descriptor(
  name='CrawlItem',
  full_name='starbelly.CrawlItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='starbelly.CrawlItem.body', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='completed_at', full_name='starbelly.CrawlItem.completed_at', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost', full_name='starbelly.CrawlItem.cost', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='starbelly.CrawlItem.duration', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='headers', full_name='starbelly.CrawlItem.headers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='starbelly.CrawlItem.job_id', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_body_compressed', full_name='starbelly.CrawlItem.is_body_compressed', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='started_at', full_name='starbelly.CrawlItem.started_at', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='starbelly.CrawlItem.status_code', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='starbelly.CrawlItem.url', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url_can', full_name='starbelly.CrawlItem.url_can', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url_hash', full_name='starbelly.CrawlItem.url_hash', index=11,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sync_token', full_name='starbelly.CrawlItem.sync_token', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CRAWLITEM_HEADERSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=369,
)


_JOBSTATUS_HTTPSTATUSCOUNTSENTRY = _descriptor.Descriptor(
  name='HttpStatusCountsEntry',
  full_name='starbelly.JobStatus.HttpStatusCountsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='starbelly.JobStatus.HttpStatusCountsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='starbelly.JobStatus.HttpStatusCountsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=684,
)

_JOBSTATUS = _descriptor.Descriptor(
  name='JobStatus',
  full_name='starbelly.JobStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='starbelly.JobStatus.job_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='starbelly.JobStatus.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='run_state', full_name='starbelly.JobStatus.run_state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_count', full_name='starbelly.JobStatus.item_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='http_success_count', full_name='starbelly.JobStatus.http_success_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='http_error_count', full_name='starbelly.JobStatus.http_error_count', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exception_count', full_name='starbelly.JobStatus.exception_count', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='http_status_counts', full_name='starbelly.JobStatus.http_status_counts', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_JOBSTATUS_HTTPSTATUSCOUNTSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=684,
)


_JOBSTATUSES = _descriptor.Descriptor(
  name='JobStatuses',
  full_name='starbelly.JobStatuses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statuses', full_name='starbelly.JobStatuses.statuses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=739,
)

_CRAWLITEM_HEADERSENTRY.containing_type = _CRAWLITEM
_CRAWLITEM.fields_by_name['headers'].message_type = _CRAWLITEM_HEADERSENTRY
_JOBSTATUS_HTTPSTATUSCOUNTSENTRY.containing_type = _JOBSTATUS
_JOBSTATUS.fields_by_name['run_state'].enum_type = _JOBRUNSTATE
_JOBSTATUS.fields_by_name['http_status_counts'].message_type = _JOBSTATUS_HTTPSTATUSCOUNTSENTRY
_JOBSTATUSES.fields_by_name['statuses'].message_type = _JOBSTATUS
DESCRIPTOR.message_types_by_name['CrawlItem'] = _CRAWLITEM
DESCRIPTOR.message_types_by_name['JobStatus'] = _JOBSTATUS
DESCRIPTOR.message_types_by_name['JobStatuses'] = _JOBSTATUSES
DESCRIPTOR.enum_types_by_name['JobRunState'] = _JOBRUNSTATE

CrawlItem = _reflection.GeneratedProtocolMessageType('CrawlItem', (_message.Message,), dict(

  HeadersEntry = _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), dict(
    DESCRIPTOR = _CRAWLITEM_HEADERSENTRY,
    __module__ = 'protobuf.shared_pb2'
    # @@protoc_insertion_point(class_scope:starbelly.CrawlItem.HeadersEntry)
    ))
  ,
  DESCRIPTOR = _CRAWLITEM,
  __module__ = 'protobuf.shared_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.CrawlItem)
  ))
_sym_db.RegisterMessage(CrawlItem)
_sym_db.RegisterMessage(CrawlItem.HeadersEntry)

JobStatus = _reflection.GeneratedProtocolMessageType('JobStatus', (_message.Message,), dict(

  HttpStatusCountsEntry = _reflection.GeneratedProtocolMessageType('HttpStatusCountsEntry', (_message.Message,), dict(
    DESCRIPTOR = _JOBSTATUS_HTTPSTATUSCOUNTSENTRY,
    __module__ = 'protobuf.shared_pb2'
    # @@protoc_insertion_point(class_scope:starbelly.JobStatus.HttpStatusCountsEntry)
    ))
  ,
  DESCRIPTOR = _JOBSTATUS,
  __module__ = 'protobuf.shared_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.JobStatus)
  ))
_sym_db.RegisterMessage(JobStatus)
_sym_db.RegisterMessage(JobStatus.HttpStatusCountsEntry)

JobStatuses = _reflection.GeneratedProtocolMessageType('JobStatuses', (_message.Message,), dict(
  DESCRIPTOR = _JOBSTATUSES,
  __module__ = 'protobuf.shared_pb2'
  # @@protoc_insertion_point(class_scope:starbelly.JobStatuses)
  ))
_sym_db.RegisterMessage(JobStatuses)


_CRAWLITEM_HEADERSENTRY.has_options = True
_CRAWLITEM_HEADERSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_JOBSTATUS_HTTPSTATUSCOUNTSENTRY.has_options = True
_JOBSTATUS_HTTPSTATUSCOUNTSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
